#![cfg(test)]

use std::sync::{Mutex, PoisonError};

use amm_pool_contract::{ConstantProductPool, ConstantProductPoolClient};
use budget_macros::{
    budget_cpu_lt, budget_lt, budget_mem_lt, budget_scaling, budget_write_bytes_lt,
};
use soroban_sdk::{testutils::Address as _, Address, Env};

/// Serialises all JSON-config tests so they never read stale `budget.json`
/// content written by another test running in parallel.
static BUDGET_JSON_LOCK: Mutex<()> = Mutex::new(());

/// A Drop guard that writes `budget.json` on creation and removes it on drop
/// (including during stack unwinding from a panic). The `_lock` field prevents
/// other JSON-config tests from overwriting the file while the assertion runs.
struct BudgetJsonGuard {
    _lock: std::sync::MutexGuard<'static, ()>,
}

impl BudgetJsonGuard {
    fn create(content: &str) -> Self {
        let lock = BUDGET_JSON_LOCK
            .lock()
            .unwrap_or_else(PoisonError::into_inner);
        std::fs::write("budget.json", content).expect("failed to write budget.json");
        BudgetJsonGuard { _lock: lock }
    }
}

impl Drop for BudgetJsonGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file("budget.json");
    }
}

/// Path to the workspace-root `tier-a-limits.env` relative to this test's
/// CWD. The file is auto-generated by `cargo budget-report --derive-limits`
/// (see [derive.rs]). Every `env_file = TIER_A_LIMITS_FILE` annotation in
/// this crate reads exactly the keys here, with provenance documented in the
/// sibling `tier-a-limits.provenance.md`.
const TIER_A_LIMITS_FILE: &str = "../tier-a-limits.env";

fn setup_wasm(env: &Env) -> (ConstantProductPoolClient<'_>, Address) {
    let wasm_path = "../target/wasm32v1-none/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found, did you run cargo build?");
    // AUDIT (Issue #92): `soroban_sdk::Env::register_contract_wasm` is deprecated in soroban-sdk 22.x
    // in favor of `Env::register`. However, `Env::register` only registers Rust contract types for
    // in-memory host execution, whereas `register_contract_wasm` remains the sole API in soroban-sdk 22.x
    // for registering raw precompiled `.wasm` byte slices into the test environment VM. Because WASM-level
    // execution is required for accurate CPU/memory budget measurements (raw Rust estimates undercount costs),
    // `register_contract_wasm` with `#[allow(deprecated)]` remains necessary until soroban-sdk provides
    // a non-deprecated replacement for raw WASM byte registration.
    #[allow(deprecated)]
    let contract_id = env.register_contract_wasm(None, wasm.as_slice());
    let client = ConstantProductPoolClient::new(env, &contract_id);

    let user = Address::generate(env);

    client.initialize();

    env.mock_all_auths();

    env.cost_estimate().budget().reset_unlimited();

    (client, user)
}

#[test]
fn test_budget_raw_rust() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    client.do_expensive_work(&10_000);

    let budget = env.cost_estimate().budget();
    println!("=== RAW RUST LOCAL ===");
    println!("CPU instructions: {}", budget.cpu_instruction_cost());
    println!("Memory bytes: {}", budget.memory_bytes_cost());
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU")]
fn test_budget_wasm() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

/// Measures CPU instruction cost of `do_expensive_work` across multiple input
/// sizes in WASM mode, for gap-vs-input-size analysis.
#[test]
fn test_measure_gap_vs_input_size() {
    let wasm_path = "../target/wasm32-unknown-unknown/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found");
    let sizes = [1000, 10000, 50000, 100000];

    for &n in &sizes {
        // --- Wasm measurement ---
        let env = Env::default();
        #[allow(deprecated)]
        let contract_id = env.register_contract_wasm(None, wasm.as_slice());
        let client = ConstantProductPoolClient::new(&env, &contract_id);
        env.cost_estimate().budget().reset_unlimited();
        client.do_expensive_work(&n);
        let wasm_cpu = env.cost_estimate().budget().cpu_instruction_cost();
        println!("  n={:>6} | local WASM CPU: {:>10}", n, wasm_cpu);
    }
}

#[test]
#[budget_lt(
    cpu = env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__DEPOSIT__CPU",
    mem = env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__DEPOSIT__MEM"
)]
fn test_budget_require_auth_deposit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU")]
fn test_budget_require_auth_swap() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU")]
fn test_budget_require_auth_withdraw() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__REQUIRE_AUTH_ONLY__CPU")]
fn test_budget_require_auth_isolated() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[budget_mem_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__REQUIRE_AUTH_ONLY__MEM")]
fn test_budget_require_auth_isolated_mem() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000)] // Deliberate regression: require_auth costs well above 1K CPU
fn test_budget_require_auth_deliberate_regression_cpu() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)] // Deliberate regression: any real memory cost exceeds an impossible 1-byte limit
fn test_budget_require_auth_deliberate_regression_mem() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__EXTEND_INSTANCE_TTL__CPU")]
fn test_budget_extend_ttl_isolated() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[budget_mem_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__EXTEND_INSTANCE_TTL__MEM")]
fn test_budget_extend_ttl_isolated_mem() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000)] // Deliberate regression: extend_ttl costs well above 1K CPU
fn test_budget_extend_ttl_deliberate_regression_cpu() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)] // Deliberate regression: any real memory cost exceeds an impossible 1-byte limit
fn test_budget_extend_ttl_deliberate_regression_mem() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU")]
fn test_budget_macro_gated() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000000)]
fn test_budget_macro_deliberate_regression() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)]
fn test_budget_macro_mem_deliberate_regression() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env = "TEST_MAX_CPU")]
fn test_budget_macro_dynamic_env() {
    let budget_env_resolve = |var: &str| -> Option<String> {
        if var == "TEST_MAX_CPU" {
            Some("3000000".to_string())
        } else {
            None
        }
    };
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env = "TEST_MAX_CPU_FALLBACK")]
fn test_budget_macro_dynamic_env_fallback() {
    let budget_env_resolve = |_var: &str| -> Option<String> { None };
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

/// Fixture: env-var form of the macro actually enforces the limit.
///
/// The two env-var tests above prove that a passing value passes and that
/// an unset variable defaults to `u64::MAX` (passing unconditionally).
/// Neither demonstrates the critical property — that when the environment
/// variable returns a value *below* the measured WASM cost, the macro
/// **must** panic.  Without this test, a future refactor of the
/// env-parsing path could silently stop enforcing env-provided limits.
///
/// This test shadows the default `budget_env_resolve` (which reads real
/// process env vars) with a closure that returns `"1"` — an impossibly
/// low CPU budget — so the macro assertion always fires.
#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(env = "BUDGET_ENFORCEMENT_DELIBERATE_FAIL")]
fn test_budget_macro_dynamic_env_deliberate_regression() {
    let budget_env_resolve = |var: &str| -> Option<String> {
        if var == "BUDGET_ENFORCEMENT_DELIBERATE_FAIL" {
            Some("1".to_string())
        } else {
            None
        }
    };
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

// ---------------------------------------------------------------------------
// JSON config tests
// ---------------------------------------------------------------------------

#[test]
#[budget_cpu_lt(config = "cpu_instructions")]
fn test_budget_macro_json_config_valid() {
    let _guard = BudgetJsonGuard::create(r#"{"cpu_instructions": 3000000}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_mem_lt(config = "memory_bytes")]
fn test_budget_macro_json_config_mem_valid() {
    let _guard = BudgetJsonGuard::create(r#"{"memory_bytes": 5000000}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(config = "non_existent_key")]
fn test_budget_macro_json_config_missing_key() {
    // When the requested key is absent from budget.json, the fallback
    // is u64::MAX ("no limit"), so the test passes without enforcing a
    // ceiling.
    let _guard = BudgetJsonGuard::create(r#"{"some_other_key": 100}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(config = "cpu_instructions_deliberate")]
fn test_budget_macro_json_config_deliberate_regression() {
    let _guard = BudgetJsonGuard::create(r#"{"cpu_instructions_deliberate": 1}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(expected = "key 'cpu_instructions' not found or invalid in budget.json")]
#[budget_cpu_lt(config = "cpu_instructions")]
fn test_budget_macro_json_config_missing_key_empty_config() {
    // Empty JSON object → requested key won't be found → fallback to
    // u64::MAX ("no limit").  The test passes, but no ceiling is
    // enforced.
    let _guard = BudgetJsonGuard::create(r#"{}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(expected = "key 'cpu_instructions' not found or invalid in budget.json")]
#[budget_cpu_lt(config = "cpu_instructions")]
fn test_budget_macro_json_config_invalid_json() {
    // Malformed JSON → parsing fails → fallback to u64::MAX ("no limit").
    // The test passes, but no ceiling is enforced.
    let _guard = BudgetJsonGuard::create(r#"this is not valid json at all"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

// ---------------------------------------------------------------------------
// Macro hygiene regression test
//
// Verify that #[budget_cpu_lt] and #[budget_mem_lt] do not leak their
// injected temporaries (budget, cpu_cost, mem_cost, limit_u64) into the
// user's namespace by declaring identically-named locals in the test body.
// These tests must compile and assert correctly.
// ---------------------------------------------------------------------------

#[test]
#[budget_cpu_lt(5000000)]
fn test_macro_hygiene_cpu_shadows_budget_and_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    // Deliberately shadow the macro's injected identifiers.
    let budget = "this_is_not_a_soroban_budget";
    let cpu_cost = "also_not_a_cost";
    let limit_u64 = 9999;

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    // Verify our shadowing locals are intact after the macro's injected
    // assertions run.
    assert_eq!(budget, "this_is_not_a_soroban_budget");
    assert_eq!(cpu_cost, "also_not_a_cost");
    assert_eq!(limit_u64, 9999);
}

#[test]
#[budget_mem_lt(2000000)]
fn test_macro_hygiene_mem_shadows_budget_and_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    // Deliberately shadow the macro's injected identifiers.
    let budget = "shadowed_budget";
    let mem_cost = "shadowed_mem_cost";
    let limit_u64 = 42;

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    assert_eq!(budget, "shadowed_budget");
    assert_eq!(mem_cost, "shadowed_mem_cost");
    assert_eq!(limit_u64, 42);
}

#[test]
#[budget_write_bytes_lt(5_000_000)]
fn test_macro_hygiene_write_bytes_shadows_budget_and_limit() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    // Deliberately shadow the macro's injected identifiers.
    let budget = "i_am_a_string_not_a_budget";
    let write_bytes_cost = "also_string_not_cost";
    let limit_u64 = 777;

    client.do_write_heavy_work(&50);

    assert_eq!(budget, "i_am_a_string_not_a_budget");
    assert_eq!(write_bytes_cost, "also_string_not_cost");
    assert_eq!(limit_u64, 777);
}

/// Fixture: contract invocation stays within the read bytes budget.
///
/// Runs a deposit + swap + withdraw cycle against the WASM contract and
/// asserts that the ledger read bytes reported by
/// `env.cost_estimate().resources().read_bytes` do not exceed a generous
/// upper bound.  This test is expected to pass under normal conditions and
/// acts as a regression guard that will fail if storage reads grow
/// unexpectedly.
#[test]
fn test_read_bytes_budget_within_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    let read_bytes = env.cost_estimate().resources().read_bytes;
    println!("Read bytes (WASM deposit+swap+withdraw): {read_bytes}");

    // Generous upper bound (measured ~20,236 locally) — tighten once a clean baseline is recorded.
    assert!(
        read_bytes < 21_000,
        "Read bytes {read_bytes} exceeded the expected limit of 21,000 \
    // Generous upper bound (measured ~20,236 on CI) — tighten once a clean baseline is recorded.
    assert!(
        read_bytes < 25_000,
        "Read bytes {read_bytes} exceeded the expected limit of 25,000 \
         - local estimate, real network cost may differ significantly in either direction"
    );
}

/// Fixture: deliberate regression — contract exceeds the read bytes budget.
///
/// Sets an impossibly tight read bytes limit (1 byte) to demonstrate what a
/// read-bytes budget breach looks like.  The `#[should_panic]` attribute
/// documents the expected failure message so that the test suite treats this
/// as a passing regression fixture rather than a real failure.
#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
fn test_read_bytes_budget_exceeds_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    let read_bytes = env.cost_estimate().resources().read_bytes;
    println!("Read bytes (deliberate regression): {read_bytes}");

    // Deliberately impossible limit: any real WASM invocation will read more
    // than 1 byte from ledger storage, so this assertion always fires.
    let limit: u32 = 1;
    assert!(
        read_bytes < limit,
        "Read bytes {read_bytes} exceeded the expected limit of {limit} \
         - local estimate, real network cost may differ significantly in either direction"
    );
}

// =======================================================================
// Failing budget assertion tests — Issue #48
// =======================================================================

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1)]
fn test_budget_cpu_fails_when_exceeded() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();
    client.burn_resources(&500);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)]
fn test_budget_mem_fails_when_exceeded() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();
    client.burn_resources(&500);
}

#[test]
#[budget_cpu_lt(18_446_744_073_709_551_615)]
fn test_budget_cpu_passes_when_under_limit() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();
    client.burn_resources(&10);
}

#[test]
#[budget_mem_lt(18_446_744_073_709_551_615)]
fn test_budget_mem_passes_when_under_limit() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();
    client.burn_resources(&10);
/// Local WASM measurement capturing the memory-bytes cost of the pure
/// allocation fixture `allocate_vec` for issue #122.
///
/// The test mirrors `test_budget_require_auth_isolated_mem` in shape —
/// registers the WASM, calls the fixture, asserts the limit via the
/// `budget_mem_lt` macro driven by an `env_file` key, and emits the
/// measured figure to stderr so the upstream-measurement workflow can
/// capture it via `--nocapture`. The CSAT cost (allocation size) is
/// derived from `cost_estimate().budget().memory_bytes_cost()` after
/// `setup_wasm`'s `reset_unlimited()` has cleared the default test budget.
#[test]
#[budget_mem_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__ALLOCATE_VEC__MEM")]
fn test_measure_memory_bytes_local_for_issue_122() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    let result = client.allocate_vec(&10_000_u32);
    assert_eq!(result, 10_000, "allocate_vec returns v.len()");

    let mem_bytes = env.cost_estimate().budget().memory_bytes_cost();
    eprintln!("MEM_LOCAL: {mem_bytes} bytes (issue #122 fixture)");
}

/// Measures the local WASM read-bytes cost of `do_read_heavy_work` for the
/// storage-read gap measurement table in `MEASUREMENTS.md`.
///
/// Writes 100 keys (256 bytes each) to instance storage, then reads them
/// all back.  The read-bytes figure is the isolated local estimate for the
/// storage-read gap analysis; the CPU and memory figures are captured
/// alongside so the entry has parity with the existing calibration table.
///
/// # Running
///
/// ```bash
/// cargo build --target wasm32-unknown-unknown --release -p amm-pool-contract
/// cargo test -p amm-pool-contract test_storage_read_wasm_local -- --nocapture
/// ```
#[test]
fn test_storage_read_wasm_local() {
    let wasm_path = "../target/wasm32-unknown-unknown/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found, did you run cargo build?");

    let env = Env::default();
    #[allow(deprecated)]
    let contract_id = env.register_contract_wasm(None, wasm.as_slice());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    // 100 keys × 256 bytes = 25 600 bytes of reads, plus per-key overhead.
    client.do_read_heavy_work(&100);

    let budget = env.cost_estimate().budget();
    let read_bytes = env.cost_estimate().resources().read_bytes;
    let cpu = budget.cpu_instruction_cost();
    let mem = budget.memory_bytes_cost();

    println!("=== STORAGE_READ_WASM_LOCAL ===");
    println!("READ_BYTES={}", read_bytes);
    println!("CPU_INSTRUCTIONS={}", cpu);
    println!("MEMORY_BYTES={}", mem);
}

// ---------------------------------------------------------------------------
// Budget scaling assertion fixtures
//
// These tests exercise the `#[budget_scaling(…)]` attribute, which measures
// CPU cost across multiple input sizes and checks that the observed growth
// matches a declared model (linear / quadratic) within a tolerance.
// ---------------------------------------------------------------------------

/// A genuinely linear operation: summing i² for i in 0..size.
/// Cost should grow roughly linearly with size.
#[budget_scaling(sizes = [10, 100, 500], model = linear, tolerance = 0.5)]
fn scaling_linear_passes(env: soroban_sdk::Env, size: u32) {
    let mut total: u32 = 0;
    for i in 0..size {
        total = total.wrapping_add(i.wrapping_mul(i));
    }
}

/// A deliberately quadratic (O(n²)) operation tested against the linear
/// model with tight tolerance — this fixture is expected to panic.
///
/// The nested loop makes cost grow as n², so the ratio check against a
/// linear model with a 20 % tolerance bound must fail.
#[budget_scaling(sizes = [10, 100], model = linear, tolerance = 0.2)]
#[should_panic(expected = "Scaling check failed")]
fn scaling_quadratic_fails_linear_check(env: soroban_sdk::Env, size: u32) {
    let mut total: u32 = 0;
    for _ in 0..size {
        for i in 0..size {
            total = total.wrapping_add(i.wrapping_mul(i));
        }
    }
}
